import React from "react";
import Input from "./Input";

const DynamicForm = () => {
  const fieldConfig = [
    {
      fieldcatalogno: "001091",
      cocode: "",
      processcode: "",
      transactioncode: "PSCPO",
      userid: "",
      inputlength: 15,
      controlwidth: 140,
      labelwidth: 120,
      anchor: "",
      tabindex: 0,
      controltype: "TXT",
      applicationdatatype: "STR",
      ontooltip: false,
      onlabel: false,
      visible: 1,
      disable: 0,
      enbaftrclick: 1,
      attachmentrequired: false,
      quickfactrequired: false,
      quickfacts: null,
      opendocrequired: false,
      opendoc: null,
      helpobject: "",
      reportobject: "",
      flexobject: "",
      fieldid: "purchaseorderno",
      dropdown: 0,
      helpwhere: "",
      displaytexttable: "",
      baseonsql: false,
      baseontable: false,
      displayhelpobject: "",
      fielddisplay: "",
      fieldwhere: "",
      sql: "",
      label: "Purchase Order No",
      helpobjectlang: "",
      reportobjectlang: "",
      flexobjectlang: "",
      defaultvalue: "",
      ismandatorybeforecreate: false,
      ismandatoryaftercreate: false,
      subform: false,
      toolbarkey: "",
      langno: "EN",
      financialdimensionrequired: false,
    },
    {
      fieldcatalogno: "001092",
      cocode: "",
      processcode: "",
      transactioncode: "PSCPO",
      userid: "",
      inputlength: 20,
      controlwidth: 160,
      labelwidth: 120,
      anchor: "",
      tabindex: 1,
      controltype: "DROPDOWN",
      applicationdatatype: "STR",
      ontooltip: false,
      onlabel: false,
      visible: 1,
      disable: 0,
      enbaftrclick: 1,
      attachmentrequired: false,
      quickfactrequired: false,
      quickfacts: null,
      opendocrequired: false,
      opendoc: null,
      helpobject: "",
      reportobject: "",
      flexobject: "",
      fieldid: "invoiceNo",
      dropdown: 1,
      helpwhere: "",
      displaytexttable: "InvoiceTable",
      baseonsql: true,
      baseontable: true,
      displayhelpobject: "",
      fielddisplay: "InvoiceNumber",
      fieldwhere: "",
      sql: "SELECT InvoiceNumber FROM InvoiceTable",
      label: "Invoice No",
      helpobjectlang: "",
      reportobjectlang: "",
      flexobjectlang: "",
      defaultvalue: "",
      ismandatorybeforecreate: false,
      ismandatoryaftercreate: false,
      subform: false,
      toolbarkey: "",
      langno: "EN",
      financialdimensionrequired: false,
    },
    {
      fieldcatalogno: "001093",
      cocode: "",
      processcode: "",
      transactioncode: "PSCPO",
      userid: "",
      inputlength: 12,
      controlwidth: 140,
      labelwidth: 120,
      anchor: "",
      tabindex: 2,
      controltype: "DATE",
      applicationdatatype: "DAT",
      ontooltip: false,
      onlabel: false,
      visible: 1,
      disable: 0,
      enbaftrclick: 1,
      attachmentrequired: false,
      quickfactrequired: false,
      quickfacts: null,
      opendocrequired: false,
      opendoc: null,
      helpobject: "",
      reportobject: "",
      flexobject: "",
      fieldid: "invoiceDate",
      dropdown: 0,
      helpwhere: "",
      displaytexttable: "",
      baseonsql: false,
      baseontable: false,
      displayhelpobject: "",
      fielddisplay: "",
      fieldwhere: "",
      sql: "",
      label: "Invoice Date",
      helpobjectlang: "",
      reportobjectlang: "",
      flexobjectlang: "",
      defaultvalue: "",
      ismandatorybeforecreate: false,
      ismandatoryaftercreate: false,
      subform: false,
      toolbarkey: "",
      langno: "EN",
      financialdimensionrequired: false,
    },
    {
      fieldcatalogno: "001094",
      cocode: "",
      processcode: "",
      transactioncode: "PSCPO",
      userid: "",
      inputlength: 8,
      controlwidth: 120,
      labelwidth: 120,
      anchor: "",
      tabindex: 3,
      controltype: "NUM",
      applicationdatatype: "INT",
      ontooltip: false,
      onlabel: false,
      visible: 1,
      disable: 0,
      enbaftrclick: 1,
      attachmentrequired: false,
      quickfactrequired: false,
      quickfacts: null,
      opendocrequired: false,
      opendoc: null,
      helpobject: "",
      reportobject: "",
      flexobject: "",
      fieldid: "itemCode",
      dropdown: 0,
      helpwhere: "",
      displaytexttable: "",
      baseonsql: false,
      baseontable: false,
      displayhelpobject: "",
      fielddisplay: "",
      fieldwhere: "",
      sql: "",
      label: "Item Code",
      helpobjectlang: "",
      reportobjectlang: "",
      flexobjectlang: "",
      defaultvalue: "",
      ismandatorybeforecreate: false,
      ismandatoryaftercreate: false,
      subform: false,
      toolbarkey: "",
      langno: "EN",
      financialdimensionrequired: false,
    },
    {
      fieldcatalogno: "001095",
      cocode: "",
      processcode: "",
      transactioncode: "PSCPO",
      userid: "",
      inputlength: 18,
      controlwidth: 150,
      labelwidth: 120,
      anchor: "",
      tabindex: 4,
      controltype: "TXT",
      applicationdatatype: "STR",
      ontooltip: false,
      onlabel: false,
      visible: 1,
      disable: 0,
      enbaftrclick: 1,
      attachmentrequired: false,
      quickfactrequired: false,
      quickfacts: null,
      opendocrequired: false,
      opendoc: null,
      helpobject: "",
      reportobject: "",
      flexobject: "",
      fieldid: "itemDescription",
      dropdown: 0,
      helpwhere: "",
      displaytexttable: "",
      baseonsql: false,
      baseontable: false,
      displayhelpobject: "",
      fielddisplay: "",
      fieldwhere: "",
      sql: "",
      label: "Item Description",
      helpobjectlang: "",
      reportobjectlang: "",
      flexobjectlang: "",
      defaultvalue: "",
      ismandatorybeforecreate: false,
      ismandatoryaftercreate: false,
      subform: false,
      toolbarkey: "",
      langno: "EN",
      financialdimensionrequired: false,
    },
  ];

  return (
    <div className="p-20">
    <h1 className="text-2xl font-semibold">Heading </h1>
      <form>
        {fieldConfig.map((field) => (
          <Input key={field.tabindex} config={field} />
        ))}
      </form>
    </div>
  );
};

export default DynamicForm;
